apiVersion: v1
kind: Service
metadata:
  name: cloudflared-metrics
  namespace: cloudflare
  labels:
    app.kubernetes.io/name: cloudflared
    app.kubernetes.io/part-of: cloudflare-tunnel
spec:
  type: ClusterIP
  selector:
    app: cloudflared
  ports:
    - name: metrics
      port: 2000
      targetPort: metrics
      protocol: TCP
