apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"server","app.kubernetes.io/instance":"unity-catalog","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"unitycatalog","app.kubernetes.io/version":"main","helm.sh/chart":"unitycatalog-0.0.1-pre.1"},"name":"unity-catalog-unitycatalog-server","namespace":"default"},"spec":{"ports":[{"name":"api","port":8080,"protocol":"TCP","targetPort":"api"}],"selector":{"app.kubernetes.io/component":"server","app.kubernetes.io/instance":"unity-catalog","app.kubernetes.io/name":"unitycatalog"},"type":"ClusterIP"}}
  creationTimestamp: "2026-01-12T05:34:43Z"
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: unity-catalog
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: unitycatalog
    app.kubernetes.io/version: main
    helm.sh/chart: unitycatalog-0.0.1-pre.1
  name: unity-catalog-unitycatalog-server
  namespace: default
  resourceVersion: "1768238422838175023"
  uid: dd204346-3b91-4d11-b953-7c60945500b1
spec:
  clusterIP: 34.118.239.36
  clusterIPs:
  - 34.118.239.36
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: api
    port: 8080
    protocol: TCP
    targetPort: api
  selector:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: unity-catalog
    app.kubernetes.io/name: unitycatalog
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
