apiVersion: batch/v1
kind: Job
metadata:
  name: airflow-db-init
  namespace: default
spec:
  template:
    spec:
      containers:
      - name: airflow-db-init
        image: apache/airflow:2.7.1
        command: ["airflow", "db", "migrate"]
        env:
        - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
          value: "postgresql+psycopg2://airflow:airflow@postgres.default.svc.cluster.local/airflow"
        - name: AIRFLOW__CORE__FERNET_KEY
          value: "46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho="
      restartPolicy: OnFailure
