apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: "SparkApplication"
metadata:
  name: "random-delta-gen-fdahfgafgashfgasjdgfj"
  namespace: "default"

spec:
  type: "Python"
  mode: "cluster"
  image: "subhodeep2022/spark-bigdata:spark-4.0.1-uc-0.3.1-proper-way-v7-compatible-jars"
  imagePullPolicy: "IfNotPresent"

  # Point to a stable path copied by initContainer
  mainApplicationFile: "local:///dags/current/scripts/random_delta_gen_v2.py"

  sparkVersion: "4.0.1"

  sparkConf:
    "spark.hadoop.fs.s3a.endpoint": "http://minio.default.svc.cluster.local:9000"
    "spark.hadoop.fs.s3a.access.key": "minioadmin"
    "spark.hadoop.fs.s3a.secret.key": "minioadmin"
    "spark.hadoop.fs.s3a.path.style.access": "true"
    "spark.hadoop.fs.s3a.connection.ssl.enabled": "false"
    "spark.hadoop.fs.s3a.impl": "org.apache.hadoop.fs.s3a.S3AFileSystem"
    "spark.hadoop.fs.s3a.aws.credentials.provider": "org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider"
    "spark.sql.warehouse.dir": "s3a://test-bucket/warehouse"
    "spark.sql.catalogImplementation": "hive"
    "spark.sql.extensions": "io.delta.sql.DeltaSparkSessionExtension"
    "spark.sql.catalog.spark_catalog": "org.apache.spark.sql.delta.catalog.DeltaCatalog"
    "spark.hadoop.hive.metastore.uris": "thrift://hive-metastore.default.svc.cluster.local:9083"
    "spark.kubernetes.driver.annotation.sidecar.istio.io/inject": "false"

  volumes:
    - name: "dags-volume"
      persistentVolumeClaim:
        claimName: "airflow-dags-shared-pvc"

  initContainers:
    - name: copy-dags
      image: busybox
      command: ["sh", "-c", "rm -rf /dags/current && cp -r /dags/repo /dags/current"]
      volumeMounts:
        - name: "dags-volume"
          mountPath: "/dags"

  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "1024m"
    labels:
      version: "4.0.1"
    serviceAccount: "spark-operator-spark"
    volumeMounts:
      - name: "dags-volume"
        mountPath: "/dags"
    env:
      - name: HADOOP_CONF_DIR
        value: "/tmp"

  executor:
    cores: 1
    instances: 1
    memory: "4096m"
    labels:
      version: "4.0.1"
    volumeMounts:
      - name: "dags-volume"
        mountPath: "/dags"
    env:
      - name: HADOOP_CONF_DIR
        value: "/tmp"
