apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - airflow.yaml
  - hive.yaml
  - jupyterhub.yaml
  - airflow-git-sync.yaml
  - airflow-spark-rbac.yaml
  - airflow-rbac.yaml

  - spark-history-server.yaml

  - spark-ui-service.yaml
  - spark-connect-server.yaml
  - starrocks.yaml

configMapGenerator:
  - name: spark-config
    files:
      - configs/spark-defaults.conf
  - name: hive-config
    files:
      - configs/hive-site.xml

helmCharts:
  - name: spark-operator
    repo: https://kubeflow.github.io/spark-operator
    version: 2.4.0
    namespace: default
    releaseName: spark-operator
    includeCRDs: true
    valuesFile: spark-operator-values.yaml
    apiVersions:
      - monitoring.coreos.com/v1/PodMonitor

  - name: superset
    repo: https://apache.github.io/superset
    version: 0.12.0
    namespace: default
    releaseName: superset
    valuesFile: superset-values.yaml
