{{- if .Values.enabled }}
# ------------------------------------------------------------------------------
# Monitoring - Spark ServiceMonitor
# ------------------------------------------------------------------------------
# Part of the Cloud-Native Big Data Platform (Umbrella Chart)
#
# Description: Prometheus discovery for Spark drivers and executors metrics.
# For configuration, see: big-data-platform/values.yaml
#
# Managed via ArgoCD Sync Wave: 0
# ------------------------------------------------------------------------------

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: spark-service-monitor
  namespace: default
  labels:
    release: kube-prometheus-stack
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  jobLabel: spark-role
  selector:
    matchLabels:
      app: spark-ui
  endpoints:
  - port: spark-ui
    path: /metrics/prometheus/
    interval: 10s
    honorLabels: true
  namespaceSelector:
    matchNames:
      - default
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: spark-executor-service-monitor
  namespace: default
  labels:
    release: kube-prometheus-stack
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  jobLabel: spark-executor
  selector:
    matchLabels:
      spark-role: executor
  endpoints:
  - port: spark-blockmanager
    path: /metrics/prometheus/
    interval: 15s
    honorLabels: true
  namespaceSelector:
    matchNames:
      - default
{{- end }}
