{{- if .Values.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-dashboard-route
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`traefik.dailyblogstudio.com`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))
      kind: Rule
      services:
        - name: api@internal
          kind: TraefikService
{{- end }}
