apiVersion: batch/v1
kind: Job
metadata:
  name: airflow-db-init
  namespace: default
spec:
  template:
    spec:
      # --- Pinning to GP Node ---
      nodeSelector:
        node-role.kubernetes.io/k8s-gp-node: ""
      initContainers:
        - name: wait-for-postgres
          image: busybox:1.36
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Waiting for postgres..."
              until nc -z postgres.default.svc.cluster.local 5432; do sleep 2; done
              echo "Postgres ready!"
      containers:
        - name: airflow-init
          image: apache/airflow:2.7.1
          # This command creates the tables and a default admin user
          command: ["/bin/bash", "-c"]
          args:
            - |
              airflow db migrate && \
              airflow users create \
                --username admin \
                --firstname admin \
                --lastname admin \
                --role Admin \
                --email admin@example.com \
                --password admin
          env:
            - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
              value: "postgresql+psycopg2://airflow:airflow@postgres.default.svc.cluster.local/airflow"
      restartPolicy: OnFailure
