apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-git-sync
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-git-sync
  template:
    metadata:
      labels:
        app: airflow-git-sync
    spec:
      securityContext:
        fsGroup: 65533
        fsGroupChangePolicy: "OnRootMismatch"
      containers:
      - name: git-sync
        image: registry.k8s.io/git-sync/git-sync:v4.2.3
        securityContext:
          runAsUser: 0
          runAsGroup: 0
          allowPrivilegeEscalation: false
        args:
          - "--repo=https://github.com/sp-202/airflow-dags.git"
          - "--ref=main"
          - "--root=/dags"
          - "--link=repo"
          - "--period=60s"
          - "--webhook-method=POST"
          - "--http-bind=0.0.0.0:9533"
        volumeMounts:
        - name: dags-shared
          mountPath: /dags
      volumes:
      - name: dags-shared
        persistentVolumeClaim:
          claimName: airflow-dags-shared-pvc
