apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-webserver
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-webserver
  template:
    metadata:
      labels:
        app: airflow-webserver
    spec:
      securityContext:
        fsGroup: 50000
      containers:
      - name: airflow-webserver
        image: apache/airflow:2.7.1
        args: ["webserver"]
        env:
        - name: AIRFLOW__CORE__EXECUTOR
          value: "LocalExecutor"
        - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
          value: "postgresql+psycopg2://airflow:airflow@postgres.default.svc.cluster.local/airflow"
        - name: AIRFLOW__CORE__FERNET_KEY
          value: "46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho="
        - name: AIRFLOW__CORE__DAGS_FOLDER
          # DIRECT PATH
          value: "/opt/airflow/dags/repo"
        volumeMounts:
        - name: dags-data
          mountPath: /opt/airflow/dags

      - name: git-sync
        image: registry.k8s.io/git-sync/git-sync:v3.6.9
        securityContext:
          runAsUser: 50000
        env:
        - name: GIT_SYNC_REPO
          value: "https://github.com/sp-202/airflow-dags.git"
        - name: GIT_SYNC_BRANCH
          value: "main"
        # THE FIX: We set the root to the mount point directly
        - name: GIT_SYNC_ROOT
          value: "/opt/airflow/dags"
        - name: GIT_SYNC_DEST
          value: "repo" 
        # THE FIX: Disabling the symlink creation behavior
        - name: GIT_SYNC_LINK
          value: ""
        - name: GIT_SYNC_WAIT
          value: "60"
        volumeMounts:
        - name: dags-data
          mountPath: /opt/airflow/dags

      volumes:
      - name: dags-data
        persistentVolumeClaim:
          claimName: airflow-dags-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-scheduler
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-scheduler
  template:
    metadata:
      labels:
        app: airflow-scheduler
    spec:
      securityContext:
        fsGroup: 50000
      containers:
      - name: airflow-scheduler
        image: apache/airflow:2.7.1
        args: ["scheduler"]
        env:
        - name: AIRFLOW__CORE__EXECUTOR
          value: "LocalExecutor"
        - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
          value: "postgresql+psycopg2://airflow:airflow@postgres.default.svc.cluster.local/airflow"
        - name: AIRFLOW__CORE__FERNET_KEY
          value: "46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho="
        - name: AIRFLOW__CORE__DAGS_FOLDER
          value: "/opt/airflow/dags/repo"
        volumeMounts:
        - name: dags-data
          mountPath: /opt/airflow/dags

      - name: git-sync
        image: registry.k8s.io/git-sync/git-sync:v3.6.9
        securityContext:
          runAsUser: 50000
        env:
        - name: GIT_SYNC_REPO
          value: "https://github.com/sp-202/airflow-dags.git"
        - name: GIT_SYNC_BRANCH
          value: "main"
        - name: GIT_SYNC_ROOT
          value: "/opt/airflow/dags"
        - name: GIT_SYNC_DEST
          value: "repo"
        - name: GIT_SYNC_LINK
          value: ""
        - name: GIT_SYNC_WAIT
          value: "60"
        volumeMounts:
        - name: dags-data
          mountPath: /opt/airflow/dags

      volumes:
      - name: dags-data
        persistentVolumeClaim:
          claimName: airflow-dags-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: airflow-webserver
  namespace: default
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: web
  selector:
    app: airflow-webserver