apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-dags-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/k8s/airflow-dags"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-dags-shared-pvc
  namespace: default
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
