apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-webserver
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-webserver
  template:
    metadata:
      labels:
        app: airflow-webserver
    spec:
      securityContext:
        fsGroup: 50000 # Ensures the volume is accessible by the Airflow user
      containers:
      - name: airflow-webserver
        image: apache/airflow:2.7.1
        args: ["webserver"]
        env:
        - name: AIRFLOW__CORE__EXECUTOR
          value: "LocalExecutor"
        - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
          value: "postgresql+psycopg2://airflow:airflow@postgres.default.svc.cluster.local/airflow"
        - name: AIRFLOW__CORE__FERNET_KEY
          value: "46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho="
        - name: AIRFLOW__CORE__LOAD_EXAMPLES
          value: "True"
        - name: _AIRFLOW_DB_UPGRADE
          value: "true"
        - name: _AIRFLOW_WWW_USER_CREATE
          value: "true"
        - name: _AIRFLOW_WWW_USER_USERNAME
          value: "admin"
        - name: _AIRFLOW_WWW_USER_PASSWORD
          value: "admin"
        - name: AIRFLOW__CORE__DAGS_FOLDER
          value: "/opt/airflow/dags/repo/airflow-dags"
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: dags-data
          mountPath: /opt/airflow/dags

      - name: git-sync
        image: registry.k8s.io/git-sync/git-sync:v4.2.1
        securityContext:
          runAsUser: 50000 # Matches Airflow user ID to prevent permission errors
        args:
          - "--repo=https://github.com/sp-202/cloud-native-bigdata-stack.git"
          - "--branch=main"
          - "--wait=60"
          - "--root=/opt/airflow/dags"
          - "--dest=repo"
          - "--link=current"
        volumeMounts:
        - name: dags-data
          mountPath: /opt/airflow/dags

      volumes:
      - name: dags-data
        emptyDir: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-scheduler
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-scheduler
  template:
    metadata:
      labels:
        app: airflow-scheduler
    spec:
      securityContext:
        fsGroup: 50000
      containers:
      - name: airflow-scheduler
        image: apache/airflow:2.7.1
        args: ["scheduler"]
        env:
        - name: AIRFLOW__CORE__EXECUTOR
          value: "LocalExecutor"
        - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
          value: "postgresql+psycopg2://airflow:airflow@postgres.default.svc.cluster.local/airflow"
        - name: AIRFLOW__CORE__FERNET_KEY
          value: "46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho="
        - name: AIRFLOW__CORE__LOAD_EXAMPLES
          value: "True"
        - name: AIRFLOW__CORE__DAGS_FOLDER
          value: "/opt/airflow/dags/repo/airflow-dags"
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        volumeMounts:
        - name: dags-data
          mountPath: /opt/airflow/dags

      - name: git-sync
        image: registry.k8s.io/git-sync/git-sync:v4.2.1
        securityContext:
          runAsUser: 50000
        args:
          - "--repo=https://github.com/sp-202/cloud-native-bigdata-stack.git"
          - "--branch=main"
          - "--wait=60"
          - "--root=/opt/airflow/dags"
          - "--dest=repo"
          - "--link=current"
        volumeMounts:
        - name: dags-data
          mountPath: /opt/airflow/dags

      volumes:
      - name: dags-data
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: airflow-webserver
  namespace: default
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: web
  selector:
    app: airflow-webserver