# apiVersion: metallb.io/v1beta1
# kind: IPAddressPool
# metadata:
#   name: platform-ip-pool
#   namespace: metallb-system
# spec:
#   addresses:
#     - 3.228.1.250/32
# ---
# apiVersion: metallb.io/v1beta1
# kind: L2Advertisement
# metadata:
#   name: platform-l2-adv
#   namespace: metallb-system
# spec:
#   ipAddressPools:
#     - platform-ip-pool
