apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  # storageClassName: standard # Use standard (HDD) to avoid SSD quota

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-data-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 80Gi
  # storageClassName: standard # Use standard (HDD) to avoid SSD quota


# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: airflow-dags-pv
# spec:
#   storageClassName: local-path
#   capacity:
#     storage: 2Gi
#   accessModes:
#     - ReadWriteOnce
#   hostPath:
#     path: "/mnt/k8s/airflow-dags"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-dags-shared-pvc
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi