{{- if .Values.airflow.enabled }}
{{- $mc := .Values.airflowSecrets.metadataConnection }}
---
apiVersion: v1
kind: Secret
metadata:
  name: big-data-platform-fernet-key
  namespace: default
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
stringData:
  fernet-key: {{ .Values.airflowSecrets.fernetKey | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: big-data-platform-webserver-secret-key
  namespace: default
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
stringData:
  webserver-secret-key: {{ .Values.airflowSecrets.webserverSecretKey | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: big-data-platform-metadata
  namespace: default
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
stringData:
  connection: "postgresql+psycopg2://{{ $mc.user }}:{{ $mc.pass }}@{{ $mc.host }}:{{ $mc.port }}/{{ $mc.db }}"
{{- end }}
